apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceName: "prometheus"
  replicas: 2
  selector:
    matchLabels:
      app: prometheus 
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  
  ports:
    - port: 9090
      name: web
  clusterIP: 10.102.185.5
  clusterIPs:
  - 10.102.185.5
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  allocateLoadBalancerNodePorts: true
  selector:
    app: prometheus
status:
  loadBalancer:
    ingress:
    - hostname: localhost
