apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  type: LoadBalancer

  ports:
    - port: 9090
      name: web
  clusterIP: 10.102.185.5
  clusterIPs:
  - 10.102.185.5
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  allocateLoadBalancerNodePorts: true
  selector:
    app: prometheus
status:
  loadBalancer:
    ingress:
    - hostname: localhost
